name: refresh-data

on:
  schedule:
    - cron: '*/30 00-01 * * *'
  push:
    branches:
      - master

jobs:
  refresh-data:
    runs-on: macOS-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-pandoc@v2
      - name: Install packages
        run: Rscript -e 'install.packages(c("here", "readr", "rmarkdown", "lubridate", "fst", "remotes", "readxl", "tidyr", "dplyr", "janitor", "httr", "readsdmx", "countrycode", "RCurl", "curl"), type = "binary")'
      - name: Install readabs
        run: Rscript -e 'remotes::install_github("mattcowgill/readabs")'
      - name: Install readrba
        run: Rscript -e 'remotes::install_github("mattcowgill/readrba")'
      - name: Get data
        run: Rscript -e 'source(here::here("R", "refresh_all.R"), echo = TRUE)'
      - name: Render README
        run: Rscript -e 'rmarkdown::render(here::here("README.Rmd"))'
      - name: Commit
        run: |
          git config --global user.name 'Matt Cowgill'
          git config --global user.email 'mattcowgill@github.com'
          git add .
          git commit -m 'refreshing data' || echo "No changes to commit"
          git push || echo "No changes to commit"